name: skillit
description: A comprehensive student career development platform
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # URL Launcher for opening external links
  http: ^1.6.0
  url_launcher: ^6.3.2
  google_fonts: ^6.1.0

  # Shared Preferences
  shared_preferences: ^2.2.2
  printing: ^5.14.3
  pdf: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/skill-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/data/projects.json
    - assets/data/roadmaps.json
    - assets/data/companies.json
